# Generated by Django 4.2.7 on 2023-11-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcoursStup', '0002_alter_ecole_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Images/ecoles'),
        ),
    ]
