# Generated by Django 4.2.7 on 2023-11-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParcoursStup', '0003_alter_ecole_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecole',
            old_name='addresse',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='ecole',
            old_name='ville',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='ecole',
            old_name='departement',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='ecole',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ecole',
            old_name='photo',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='ecole',
            old_name='codePostal',
            new_name='zipCode',
        ),
    ]
