# Generated by Django 4.2.7 on 2023-11-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcoursStup', '0004_rename_addresse_ecole_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('mail', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=180)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=80)),
                ('region', models.CharField(max_length=60)),
                ('department', models.CharField(max_length=50)),
                ('zipCode', models.CharField(max_length=15)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/ecoles')),
            ],
        ),
        migrations.DeleteModel(
            name='Ecole',
        ),
    ]
