# Generated by Django 4.2.7 on 2023-11-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcoursStup', '0005_school_delete_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(default='', max_length=126),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='school'),
        ),
    ]
