# Generated by Django 4.2.7 on 2023-12-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcoursStup', '0006_school_slug_alter_school_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='zipCode',
            field=models.IntegerField(max_length=15),
        ),
    ]
