# Generated by Django 4.2.7 on 2023-12-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParcoursStup', '0007_alter_school_description_alter_school_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='password',
        ),
    ]
