# Generated by Django 4.2.7 on 2023-12-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcoursStup', '0008_remove_school_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='zipCode',
            field=models.IntegerField(),
        ),
    ]
