# Generated by Django 4.2.7 on 2023-12-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcoursStup', '0009_alter_school_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('diploma', models.CharField(max_length=120)),
                ('skills', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('school', models.ManyToManyField(to='ParcoursStup.school')),
            ],
        ),
    ]
