# Generated by Django 4.2.7 on 2023-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcoursStup', '0010_formation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='school',
        ),
        migrations.AddField(
            model_name='school',
            name='formation',
            field=models.ManyToManyField(null=True, to='ParcoursStup.formation'),
        ),
    ]
