# Generated by Django 4.2.7 on 2023-12-09 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParcoursStup', '0012_alter_school_formation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='formation',
        ),
        migrations.AddField(
            model_name='formation',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formationsSchool', to='ParcoursStup.school'),
        ),
    ]
