# Generated by Django 4.2.7 on 2023-12-09 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ParcoursStup', '0014_school_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='userSchool', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
