# Generated by Django 4.2.7 on 2023-12-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParcoursStup', '0016_rename_username_school_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='user',
        ),
    ]
