# Generated by Django 4.2.7 on 2023-12-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcoursStup', '0017_remove_school_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='slug',
            field=models.SlugField(default='', max_length=126),
            preserve_default=False,
        ),
    ]
