# Generated by Django 4.2.7 on 2023-12-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='birthday',
            field=models.DateField(default='2023-12-06'),
        ),
        migrations.AddField(
            model_name='customusers',
            name='report_card',
            field=models.FileField(blank=True, null=True, upload_to='report-card'),
        ),
    ]
