# Generated by Django 4.2.7 on 2023-12-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customusers_birthday_customusers_report_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='usertype',
            field=models.CharField(default='student', max_length=50),
            preserve_default=False,
        ),
    ]
