# Generated by Django 4.2.7 on 2023-12-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customusers_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusers',
            old_name='usertype',
            new_name='user_type',
        ),
    ]
