# Generated by Django 4.2.7 on 2023-12-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcoursStup', '0018_formation_slug'),
        ('accounts', '0006_customusers_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='formation',
            field=models.ManyToManyField(to='ParcoursStup.formation'),
        ),
    ]
