# Generated by Django 4.2.7 on 2023-12-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customusers_formation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='formation',
        ),
    ]
